### ISSUE TITLE
Crates.io

### ISSUE THREAD

**Issue by Jak2k** [vic1707/serde-versioning#2]
Is there a reason this is not on crates.io?

**Comment by vic1707** [comment]
Hi, 
the main one was that serde dependency is a git url to my own fork waiting for a PR approval, this prevents pushing to crates.io.

I was hoping my PR would get merged quickly so I publish on crates.io.
As you can see here https://github.com/serde-rs/serde/pull/2765 it got rejected but a workaround was proposed which could allow publishing to crates.io.

I'll work on it asap 😉

**Comment by vic1707** [comment]
Hi, for now I can't get it to work, no matter what I do either crates.io complains or build simply fails 😓

**Comment by vic1707** [comment]
Hi, I got it all figured out, here's the link
https://crates.io/crates/serde-versioning
the version is synced to the serde release used

**Comment by vic1707** [comment]
Closing, hopefully you were able to use the crate 👍
